name: Build + Test
on: [pull_request]

jobs:
  build:
    name: Build + Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '2.6', '2.7', '3.0', '3.1', '3.2', '3.3']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Build and test with Rake with Ruby ${{ matrix.ruby }}
        run: bundle exec rake spec
  lint:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6
      - name: Run linters
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3
          bundle exec rake rubocop
